name: "swapbotAA-relayer"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2023-09-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "./log/swapbotAA-relayer.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password:
  dbname:
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host:
  port: 6379
  password: ""
  db: 0
  pool_size: 100

ethereum:
  rpc_endpoint_addr: "wss://eth-sepolia.g.alchemy.com/v2/6Y_wOo59vIqBe8RD0NlOOZJwQtsvcaIf"
  private_rpc_endpoint_addr: "https://relay.flashbots.net"
  wallet_contract_addr: "0x90CaF385c36b19d9f2BB9B5098398b6844eff8eB"
  uniswap_router_contract_addr: "0x63A62CBFeBaADFE58CA7E876b6b72868C4aA7CB6"
  system_account_private_key: "55bc18e822225d4a701ca9e4ead6f9696d794d1bfce3a8a18ac8b306b8cf3be3"
